### ISSUE TITLE
Add a License to the project 

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/lattice-surgery-compiler#113]
As title. @gwwatkin suggested that we looks at LGPL for the compiler and AGPL for the service.

**Comment by gwwatkin** [comment]
Yeah, I suggest LGPL for the compiler because it promotes the project as remaining open source, but commercial software can still import it (counts as dynamic linking in GPL terms). And AGPL for the service and websites, which is a copyleft license that allows use and hosting by others as long as they provide their derivative work as free as well.
