### ISSUE TITLE
Refactoring `remove_y_operators_from_circuit` 

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/lattice-surgery-compiler#184]
`remove_y_operators_from_circuit` is a critical component for our compiler. Right now it contains too many moving parts which makes it hard for us to write tests. 

It also uses the `pop` mechanism that we previously decided against. It was meant to move the newly generated pi/4 rotation on the RHS towards the end of the circuit ~~so we don't have to run `apply_transformation` again~~:

https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/942c5c4010daeae4b1d815ae47c4b01770f22cc9/src/lsqecc/pauli_rotations/circuit.py#L174-L180

So I am planning to:
* Divide the whole thing into smaller parts - starting with the Y op removing logic for a single block.
* Add test. Will use examples from Litinski's but might need help with verification. 
* Remove `pop` logic. 

This is opened for discussion. LMK if I am missing anything here.

**Comment by gwwatkin** [comment]
Sounds good. I think we can avoid commuting the RHS corrective terms to the end. It's an extra level of complexity, which without the popping, which we need to remove to preserve state vectors, doesn't buy us anything.

Having this commutation loop was a bit more subtle than just avoiding one more call of the Litinski transform.  Y op removal is only correct if run after the Litinski transform, because as we move corrective terms along, they may cause more Y operators to arise. So just calling Y removal and then Litinski might not remove all Y operators.

**Comment by alexnguyenn** [comment]
@gwwatkin thanks for pointing that out. Just updated the description. 

> Y op removal is only correct if run after the Litinski transform

~~Just want to refresh my memories for this, but is there a situation where we need to run this even without Litinski being called prior?~~ Seems like the Y operators are brought out during the process of Litinski transform.
