### ISSUE TITLE
Move the Web GUI to it's own repo

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#99]
- [x] Create a new repo under the org's namespace (say `latticesurgery-com/webgui`)
- [ ] Move the Django website to the new repo
- [ ] ~~Import `lattice-surgery-compiler` with as a git submodule~~ Call the compiler as a service. (depends on #106)
- [ ] Remove unused dependencies (E.g. Django, Pyramids) to make the repo ready to be export it as a python package

**Comment by gwwatkin** [comment]
To call the compiler there will be some javascript like:
```javascript
jQuery.post("https://url.to.function/compile",
           {circuit: "...", litinskiTransform:"true",...},
           function( data ) {
                // callback to handle the function's response
               const {slices} = data;
               // Render the grid slices as it was done in the template (see below)
               // ...
});
```
How slices were rendered from the template, and now have to be rendered in js: 
https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/aa3d24a958d5ab84424d0b482d6090a5fc51eb2d/webgui/templates/lattice_view.mak#L89-L94

**Comment by Keelando** [comment]
I'm on it. It's going to take some time to de-django-ify. Some of the CSS styling, and default form selections were embedded using Django. I'll also have to learn how to generate CSRF tokens without a server. Perhaps every time someone lands on the page, some JS code runs which pings the Lambda to generate a CSRF token which is subsequently needed to use the API.  And due to the resource intensive calculations performed on the Lamda, we will probably want to throttle the requests somehow so that it doesn't get pinged repeatedly.

These are a few considerations with going serverless, some of this stuff you get for free with Backends like Django, etc. 

Honestly though, this is a good time to rebuild from scratch. So I might end up doing that instead.

**Comment by gwwatkin** [comment]
These are some good considerations. I've already started some basic de-django-ification so let me try to give you some insight.

* CSRF tokens won't be necessary because
* yes, JS code can ping lambdas. To start pinging the compiler at api.latticesurgery.com should be enough, but you can make more if you feel  you need server side services (like a database)
* Requests are throttled by configuring API Gateway. Right now I'm doing this manually in the console, but it should be possible to configure it through CloudFormation at deployment time.

Rebuilding from scratch is an option. In the interest of time I've just started porting the website to React (it's not turning out to be too complex) though I happy to give you what I have and hand off the task to you.

- Porting to React issue https://github.com/latticesurgery-com/web-ui/issues/5

**Comment by Keelando** [comment]
Yeah, I realize CSRF tokens aren't necessary until user logins. No cookies, no CSRF, essentially.

I am familar with AJAX , and unless React has its own methodologies regarding asynch HTTP requests, that is how I would do it.

**Comment by Keelando** [comment]
Completed, and replaced with issue #111
